--Name
QuestAltermannName = {
    AMName1 = "Alter Mann",
    AMName2 = "Lupa Schmakulo",
    AMName = 0,
}

--Quests
QuestAltermann1 = {
    questnameam1 = "Quest: Der Fremde Mann",
    am1 = "Hallo Fremder! Wie kann ich dir Helfen?",
    ambutton11 = "Wer bist du?",
    ambutton12 = "",
    ambutton13 = "",
    am2 = "Du möchtest Wissen wer ich bin?",
    ambutton21 = "Ja gerne!",
    ambutton22 = "Eigentlich nicht.",
    ambutton23 = "",
    am3 = "Bevor ich dir meinen Namen verrate,",
    am31 = "musst du etwas für mich erledigen.",
    ambutton31 = "Was denn?",
    ambutton32 = "Nö! Kannst mich mal!",
    ambutton33 = "",
    am32 = "Na komm schon. Tu mir diesen gefallen.",
    am33 = "Du wirst es nicht bereuen!",
    am4 = "Du sollst zu unserer Schmiedin gehen und etwas für mich abholen.",
    ambutton41 = "Alles Klar!",
    ambutton42 = "",
    ambutton43 = "",
    am5 = "Und? Warst du bei ihr?",
    ambutton51 = "Ja!",
    ambutton52 = "Noch nicht.",
    ambutton53 = "",
    am6 = "Nun da du mir ein gefallen getan hast",
    am61 = "werde ich dir meinen Namen nenen...",
    ambutton61 = "Weiter",
    ambutton62 = "",
    ambutton63 = "",
    am7 = "Mein Name lautet: ...",
    ambutton71 = "Lupa Schmakulo!",
}